import type { Metadata } from "next"
import "./globals.css"
import { ReactNode } from "react"
import { IBM_Plex_Sans, Source_Sans_3 } from "next/font/google"
import Sidebar from "@/components/layout/Sidebar"

export const metadata: Metadata = {
    title: "MatDev PM",
    description: "Generated by create next app",
}

const IBMPlexSans = IBM_Plex_Sans({
    variable: "--font-ibm",
    subsets: ["latin"],
})

const SourceSans3 = Source_Sans_3({
    variable: "--font-source-sans",
    subsets: ["latin"],
})

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
    return (
        <html lang="en">
            <body className={`${IBMPlexSans.variable} ${SourceSans3.variable}`}>
                {/*<ThemeProvider>*/}
                <div className="flex min-h-screen w-screen">
                    <Sidebar />

                    <div className="ml-19 flex min-h-screen flex-1 flex-col py-12 pr-12 pl-8">{children}</div>
                </div>
                {/*</ThemeProvider>*/}
            </body>
        </html>
    )
}

export default RootLayout
