import type { Metadata } from "next"
import "./globals.css"
import { ReactNode } from "react"
import { IBM_Plex_Sans, Source_Sans_3 } from "next/font/google"
import ThemeProvider from "@/components/layout/ThemeProvider"

export const metadata: Metadata = {
  title: "MatDev PM",
  description: "Generated by create next app",
}

const IBMPlexSans = IBM_Plex_Sans({
    variable: "--font-ibm",
    subsets: ["latin"]
})

const SourceSans3 = Source_Sans_3({
    variable: "--font-source-sans",
    subsets: ["latin"]
})

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
      <html lang="en">
        <body className={`${IBMPlexSans.variable} ${SourceSans3.variable}`}>
            <ThemeProvider>
                { children }
            </ThemeProvider>
        </body>
    </html>
  )
}

export default RootLayout
