import type { Metadata } from "next"
import "./globals.css"
import { ReactNode } from "react"
import { IBM_Plex_Sans, Source_Sans_3 } from "next/font/google"
import ThemeProvider from "@/components/layout/ThemeProvider"
import Sidebar from "@/components/layout/Sidebar";

export const metadata: Metadata = {
  title: "MatDev PM",
  description: "Generated by create next app",
}

const IBMPlexSans = IBM_Plex_Sans({
    variable: "--font-ibm",
    subsets: ["latin"]
})

const SourceSans3 = Source_Sans_3({
    variable: "--font-source-sans",
    subsets: ["latin"]
})

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
      <html lang="en">
        <body className={`${IBMPlexSans.variable} ${SourceSans3.variable}`}>
            {/*<ThemeProvider>*/}
                <div className="flex flex-nowrap gap-5">
                    <Sidebar />

                    <div className="pt-12 px-5 flex-1 w-full">
                        { children }
                    </div>
                </div>
            {/*</ThemeProvider>*/}
        </body>
    </html>
  )
}

export default RootLayout
