export type ProjectStatus = "To do" | "In progress" | "Completed"
export type ProjectPriority = "Low" | "Medium" | "High"

export type ProjectType = {
    id: number
    projectName: string
    description: string
    issueType: string
    workpackage: string
    topic: string
    startDate: string
    deadline: string
    status: ProjectStatus
    priority: ProjectPriority
    people: string[]
    budget: number
    amountSpent: number
}

export interface UserType {
    id: number
    firstName: string
    secondName: string
    email: string
    phone: string
}

export type WarningType = {
    isRead: boolean
    severity: ProjectPriority
    description: string
}

export const DUMMY_PROJECTS_DATA = [
    {
        id: 1,
        projectName: "Project Alpha",
        description: "Optio laboriosam sed voluptatem vel culpa officiis aut quis. Ut voluptate optio culpa explicabo quia. Aliquid ipsa soluta qui ea non. Adipisci est est rerum qui et.",
        issueType: "Bug",
        workpackage: "WP-01",
        topic: "Authentication error",
        startDate: "2026-01-05",
        deadline: "2026-06-15",
        status: "To do",
        priority: "High",
        people: ["John", "Emily"],
        budget: 3000,
        amountSpent: 1200,
    },
    {
        id: 2,
        projectName: "Project Beta",
        description: "Optio laboriosam sed voluptatem vel culpa officiis aut quis. Ut voluptate optio culpa explicabo quia. Aliquid ipsa soluta qui ea non. Adipisci est est rerum qui et.",
        issueType: "Feature",
        workpackage: "WP-02",
        topic: "Dashboard redesign",
        startDate: "2026-01-10",
        deadline: "2026-05-01",
        status: "In progress",
        priority: "Medium",
        people: ["Sarah"],
        budget: 3000,
        amountSpent: 1200,
    },
    {
        id: 3,
        projectName: "Project Gamma",
        description: "Optio laboriosam sed voluptatem vel culpa officiis aut quis. Ut voluptate optio culpa explicabo quia. Aliquid ipsa soluta qui ea non. Adipisci est est rerum qui et.",
        issueType: "Task",
        workpackage: "WP-03",
        topic: "API integration",
        startDate: "2026-01-12",
        deadline: "2026-09-25",
        status: "Completed",
        priority: "Low",
        people: ["Michael", "Anna"],
        budget: 3000,
        amountSpent: 1200,
    },
    {
        id: 4,
        projectName: "Project Delta",
        description: "Optio laboriosam sed voluptatem vel culpa officiis aut quis. Ut voluptate optio culpa explicabo quia. Aliquid ipsa soluta qui ea non. Adipisci est est rerum qui et.",
        issueType: "Bug",
        workpackage: "WP-01",
        topic: "Payment failure",
        startDate: "2026-01-08",
        deadline: "2027-11-18",
        status: "In progress",
        priority: "High",
        people: ["David"],
        budget: 3000,
        amountSpent: 1200,
    },
    {
        id: 5,
        projectName: "Project Epsilon",
        description: "Optio laboriosam sed voluptatem vel culpa officiis aut quis. Ut voluptate optio culpa explicabo quia. Aliquid ipsa soluta qui ea non. Adipisci est est rerum qui et.",
        issueType: "Improvement",
        workpackage: "WP-04",
        topic: "UI performance",
        startDate: "2026-01-20",
        deadline: "2026-02-05",
        status: "To do",
        priority: "Medium",
        people: ["Laura", "Chris"],
        budget: 3000,
        amountSpent: 1200,
    },
    {
        id: 6,
        projectName: "Project Zeta",
        description: "Optio laboriosam sed voluptatem vel culpa officiis aut quis. Ut voluptate optio culpa explicabo quia. Aliquid ipsa soluta qui ea non. Adipisci est est rerum qui et.",
        issueType: "Feature",
        workpackage: "WP-02",
        topic: "User roles system",
        startDate: "2026-01-11",
        deadline: "2026-10-10",
        status: "In progress",
        priority: "High",
        people: ["Tom", "Nina"],
        budget: 3000,
        amountSpent: 1200,
    },
    {
        id: 7,
        projectName: "Project Eta",
        description: "Optio laboriosam sed voluptatem vel culpa officiis aut quis. Ut voluptate optio culpa explicabo quia. Aliquid ipsa soluta qui ea non. Adipisci est est rerum qui et.",
        issueType: "Task",
        workpackage: "WP-05",
        topic: "Data export",
        startDate: "2026-01-14",
        deadline: "2026-2-28",
        status: "Completed",
        priority: "Low",
        people: ["Paul"],
        budget: 3000,
        amountSpent: 1200,
    },
    {
        id: 8,
        projectName: "Project Theta",
        description: "Optio laboriosam sed voluptatem vel culpa officiis aut quis. Ut voluptate optio culpa explicabo quia. Aliquid ipsa soluta qui ea non. Adipisci est est rerum qui et.",
        issueType: "Bug",
        workpackage: "WP-03",
        topic: "Notification delay",
        startDate: "2026-01-09",
        deadline: "2026-09-19",
        status: "Completed",
        priority: "Medium",
        people: ["Olivia"],
        budget: 3000,
        amountSpent: 1200,
    },
    {
        id: 9,
        projectName: "Project Iota",
        description: "Optio laboriosam sed voluptatem vel culpa officiis aut quis. Ut voluptate optio culpa explicabo quia. Aliquid ipsa soluta qui ea non. Adipisci est est rerum qui et.",
        issueType: "Improvement",
        workpackage: "WP-06",
        topic: "Search optimization",
        startDate: "2026-01-03",
        deadline: "2026-01-22",
        status: "In progress",
        priority: "High",
        people: ["Daniel", "Sophia"],
        budget: 3000,
        amountSpent: 1200,
    },
    {
        id: 10,
        projectName: "Project Kappa",
        description: "Optio laboriosam sed voluptatem vel culpa officiis aut quis. Ut voluptate optio culpa explicabo quia. Aliquid ipsa soluta qui ea non. Adipisci est est rerum qui et.",
        issueType: "Feature",
        workpackage: "WP-04",
        topic: "Mobile support",
        startDate: "2026-01-07",
        deadline: "2026-02-14",
        status: "To do",
        priority: "Medium",
        people: ["James", "Emma"],
        budget: 3000,
        amountSpent: 1200,
    },
] as ProjectType[]

export type TaskType = {
    id: number
    projectId: number
    name: string
    description: string
    status: ProjectStatus
    priority: ProjectPriority
    isMilestone: boolean
    startDate: string
    endDate: string
    parentId?: number
    progress: number
    taskCategory: string
    requesterId: string
}

export const DUMMY_TASKS_DATA = [
    {
        id: 1,
        projectId: 1,
        name: "Setup auth backend",
        description: "Initialize authentication service",
        status: "In progress",
        priority: "High",
        isMilestone: true,
        startDate: "2026-01-05",
        endDate: "2026-01-10",
        progress: 60,
        taskCategory: "Backend",
        requesterId: "John",
    },
    {
        id: 2,
        projectId: 1,
        name: "JWT implementation",
        description: "Add JWT login flow",
        status: "To do",
        priority: "High",
        isMilestone: false,
        startDate: "2026-01-11",
        endDate: "2026-01-20",
        parentId: 1,
        progress: 0,
        taskCategory: "Backend",
        requesterId: "Emily",
    },
    {
        id: 3,
        projectId: 1,
        name: "OAuth login",
        description: "Google OAuth integration",
        status: "To do",
        priority: "Medium",
        isMilestone: false,
        startDate: "2026-01-12",
        endDate: "2026-01-25",
        parentId: 1,
        progress: 0,
        taskCategory: "Backend",
        requesterId: "Emily",
    },

    {
        id: 4,
        projectId: 2,
        name: "Dashboard wireframes",
        description: "Create UI mockups",
        status: "Completed",
        priority: "Medium",
        isMilestone: true,
        startDate: "2026-01-10",
        endDate: "2026-01-15",
        progress: 100,
        taskCategory: "Design",
        requesterId: "Sarah",
    },
    {
        id: 5,
        projectId: 2,
        name: "Implement dashboard layout",
        description: "Build main layout",
        status: "In progress",
        priority: "High",
        isMilestone: false,
        startDate: "2026-01-16",
        endDate: "2026-02-01",
        parentId: 4,
        progress: 40,
        taskCategory: "Frontend",
        requesterId: "Sarah",
    },
    {
        id: 6,
        projectId: 2,
        name: "Charts integration",
        description: "Add charts",
        status: "To do",
        priority: "Medium",
        isMilestone: false,
        startDate: "2026-02-01",
        endDate: "2026-02-10",
        parentId: 5,
        progress: 0,
        taskCategory: "Frontend",
        requesterId: "Sarah",
    },

    {
        id: 7,
        projectId: 3,
        name: "API schema design",
        description: "Design endpoints",
        status: "Completed",
        priority: "High",
        isMilestone: true,
        startDate: "2026-01-12",
        endDate: "2026-01-18",
        progress: 100,
        taskCategory: "Backend",
        requesterId: "Michael",
    },
    {
        id: 8,
        projectId: 3,
        name: "Integrate API",
        description: "Connect frontend",
        status: "Completed",
        priority: "Medium",
        isMilestone: false,
        startDate: "2026-01-19",
        endDate: "2026-02-01",
        parentId: 7,
        progress: 100,
        taskCategory: "Integration",
        requesterId: "Anna",
    },

    {
        id: 9,
        projectId: 4,
        name: "Fix payment bug",
        description: "Resolve payment issue",
        status: "In progress",
        priority: "High",
        isMilestone: true,
        startDate: "2026-01-08",
        endDate: "2026-01-20",
        progress: 50,
        taskCategory: "Bugfix",
        requesterId: "David",
    },
    {
        id: 10,
        projectId: 4,
        name: "Add retry logic",
        description: "Improve payment reliability",
        status: "To do",
        priority: "High",
        isMilestone: false,
        startDate: "2026-01-21",
        endDate: "2026-02-01",
        parentId: 9,
        progress: 0,
        taskCategory: "Backend",
        requesterId: "David",
    },

    {
        id: 11,
        projectId: 5,
        name: "Analyze UI performance",
        description: "Check bottlenecks",
        status: "Completed",
        priority: "Medium",
        isMilestone: true,
        startDate: "2026-01-20",
        endDate: "2026-01-22",
        progress: 100,
        taskCategory: "Analysis",
        requesterId: "Laura",
    },
    {
        id: 12,
        projectId: 5,
        name: "Optimize rendering",
        description: "Improve performance",
        status: "To do",
        priority: "Medium",
        isMilestone: false,
        startDate: "2026-01-23",
        endDate: "2026-02-05",
        parentId: 11,
        progress: 0,
        taskCategory: "Frontend",
        requesterId: "Chris",
    },

    {
        id: 13,
        projectId: 6,
        name: "Design role model",
        description: "Define roles",
        status: "Completed",
        priority: "High",
        isMilestone: true,
        startDate: "2026-01-11",
        endDate: "2026-01-15",
        progress: 100,
        taskCategory: "Backend",
        requesterId: "Tom",
    },
    {
        id: 14,
        projectId: 6,
        name: "Implement RBAC",
        description: "Add permissions",
        status: "In progress",
        priority: "High",
        isMilestone: false,
        startDate: "2026-01-16",
        endDate: "2026-02-10",
        parentId: 13,
        progress: 30,
        taskCategory: "Backend",
        requesterId: "Nina",
    },

    {
        id: 15,
        projectId: 7,
        name: "Export CSV",
        description: "Basic export",
        status: "Completed",
        priority: "Low",
        isMilestone: false,
        startDate: "2026-01-14",
        endDate: "2026-01-18",
        progress: 100,
        taskCategory: "Feature",
        requesterId: "Paul",
    },
    {
        id: 16,
        projectId: 7,
        name: "Export PDF",
        description: "Advanced export",
        status: "Completed",
        priority: "Low",
        isMilestone: false,
        startDate: "2026-01-18",
        endDate: "2026-01-22",
        progress: 100,
        taskCategory: "Feature",
        requesterId: "Paul",
    },

    {
        id: 17,
        projectId: 8,
        name: "Investigate delay",
        description: "Check queue",
        status: "Completed",
        priority: "Medium",
        isMilestone: true,
        startDate: "2026-01-09",
        endDate: "2026-01-12",
        progress: 100,
        taskCategory: "Bugfix",
        requesterId: "Olivia",
    },
    {
        id: 18,
        projectId: 8,
        name: "Fix notification system",
        description: "Optimize delivery",
        status: "Completed",
        priority: "Medium",
        isMilestone: false,
        startDate: "2026-01-13",
        endDate: "2026-01-20",
        parentId: 17,
        progress: 100,
        taskCategory: "Backend",
        requesterId: "Olivia",
    },

    {
        id: 19,
        projectId: 9,
        name: "Search audit",
        description: "Analyze search",
        status: "In progress",
        priority: "High",
        isMilestone: true,
        startDate: "2026-01-03",
        endDate: "2026-01-10",
        progress: 70,
        taskCategory: "Analysis",
        requesterId: "Daniel",
    },
    {
        id: 20,
        projectId: 9,
        name: "Improve indexing",
        description: "Better search results",
        status: "In progress",
        priority: "High",
        isMilestone: false,
        startDate: "2026-01-11",
        endDate: "2026-01-22",
        parentId: 19,
        progress: 30,
        taskCategory: "Backend",
        requesterId: "Sophia",
    },

    {
        id: 21,
        projectId: 10,
        name: "Mobile layout",
        description: "Responsive UI",
        status: "To do",
        priority: "Medium",
        isMilestone: true,
        startDate: "2026-01-07",
        endDate: "2026-01-20",
        progress: 0,
        taskCategory: "Frontend",
        requesterId: "James",
    },
    {
        id: 22,
        projectId: 10,
        name: "Touch interactions",
        description: "Mobile UX",
        status: "To do",
        priority: "Medium",
        isMilestone: false,
        startDate: "2026-01-21",
        endDate: "2026-02-14",
        parentId: 21,
        progress: 0,
        taskCategory: "Frontend",
        requesterId: "Emma",
    },

    // extra filler tasks
    {
        id: 23,
        projectId: 1,
        name: "Write tests",
        description: "Unit tests",
        status: "To do",
        priority: "Medium",
        isMilestone: false,
        startDate: "2026-01-20",
        endDate: "2026-01-30",
        progress: 0,
        taskCategory: "QA",
        requesterId: "John",
    },
    {
        id: 24,
        projectId: 2,
        name: "Accessibility audit",
        description: "A11y fixes",
        status: "To do",
        priority: "Low",
        isMilestone: false,
        startDate: "2026-02-10",
        endDate: "2026-02-20",
        progress: 0,
        taskCategory: "QA",
        requesterId: "Sarah",
    },
    {
        id: 25,
        projectId: 3,
        name: "Logging system",
        description: "Add logs",
        status: "Completed",
        priority: "Low",
        isMilestone: false,
        startDate: "2026-02-01",
        endDate: "2026-02-05",
        progress: 100,
        taskCategory: "Backend",
        requesterId: "Anna",
    },
    {
        id: 26,
        projectId: 4,
        name: "Error monitoring",
        description: "Integrate Sentry",
        status: "In progress",
        priority: "Medium",
        isMilestone: false,
        startDate: "2026-02-01",
        endDate: "2026-02-10",
        progress: 20,
        taskCategory: "DevOps",
        requesterId: "David",
    },
    {
        id: 27,
        projectId: 5,
        name: "Lazy loading",
        description: "Optimize bundles",
        status: "To do",
        priority: "Medium",
        isMilestone: false,
        startDate: "2026-02-06",
        endDate: "2026-02-15",
        progress: 0,
        taskCategory: "Frontend",
        requesterId: "Chris",
    },
    {
        id: 28,
        projectId: 6,
        name: "Audit permissions",
        description: "Security review",
        status: "To do",
        priority: "High",
        isMilestone: false,
        startDate: "2026-02-10",
        endDate: "2026-02-20",
        progress: 0,
        taskCategory: "Security",
        requesterId: "Nina",
    },
    {
        id: 29,
        projectId: 8,
        name: "Retry queue",
        description: "Improve reliability",
        status: "Completed",
        priority: "Low",
        isMilestone: false,
        startDate: "2026-01-20",
        endDate: "2026-01-25",
        progress: 100,
        taskCategory: "Backend",
        requesterId: "Olivia",
    },
    {
        id: 30,
        projectId: 10,
        name: "Device testing",
        description: "Test on devices",
        status: "To do",
        priority: "Medium",
        isMilestone: false,
        startDate: "2026-02-15",
        endDate: "2026-02-25",
        progress: 0,
        taskCategory: "QA",
        requesterId: "Emma",
    },
] as TaskType[]

export const DUMMY_USERS_DATA: UserType[] = [
    { id: 1, firstName: "Jan", secondName: "Kowalski", email: "jan.kowalski@gmail.com", phone: "123-123-123" },
    { id: 2, firstName: "Anna", secondName: "Nowak", email: "anna.nowak@gmail.com", phone: "222-333-444" },
    { id: 3, firstName: "Piotr", secondName: "Wojcik", email: "piotr.wojcik@gmail.com", phone: "555-666-777" },
    { id: 4, firstName: "Maria", secondName: "Kaminska", email: "maria.kaminska@gmail.com", phone: "888-999-111" },
    { id: 5, firstName: "Tomasz", secondName: "Zielinski", email: "tomasz.zielinski@gmail.com", phone: "444-555-666" },
    { id: 6, firstName: "Katarzyna", secondName: "Lewandowska", email: "k.lewandowska@gmail.com", phone: "777-111-222" },
]

export const DUMMY_WARNING_DATA: WarningType[] = [
    {
        isRead: false,
        severity: "Low",
        description: "Minor delay in task, no impact on project timeline.",
    },
    {
        isRead: false,
        severity: "Medium",
        description: "Risk of exceeding budget in the current project phase.",
    },
    {
        isRead: false,
        severity: "High",
        description: "Integration bug may block key functionality.",
    },
    {
        isRead: true,
        severity: "High",
        description: "Critical dependency failure affecting multiple modules.",
    },
    {
        isRead: true,
        severity: "Medium",
        description: "Missing technical documentation for API module updates.",
    },
]

export const PROJECT_STATUS_OPTIONS: ProjectStatus[] = ["To do", "In progress", "Completed"]
export const PROJECT_PRIORITY_OPTIONS: ProjectPriority[] = ["Low", "Medium", "High"]
export const PROJECT_TOPIC_OPTIONS = ["Authentication error", "Dashboard redesign", "API integration", "Payment failure", "UI performance", "User roles system"]
export const PROJECT_ISSUE_TYPE_OPTIONS = ["Bug", "Feature", "Task", "Improvement"]
export const PROJECT_WORKPACKAGE_OPTIONS = ["WP-01", "WP-02", "WP-03", "WP-04", "WP-05", "WP-06"]
